version: "3.6"
services:
    app:
        container_name: app.angular
        image: www/angular
        build: 
            context: ./docker
            args:
                - email=gmail@metlinskyi.com
                - name=Roman Metlinskyi
        ports:
            - 80:80         # prod  http://localhost/  
            - 8080:8080     # dev   http://localhost:8080/ 
        volumes:
            - .:/usr/share/app
        env_file:
            - ./docker/variables.env