version: "3.6"
services:
    app:
        container_name: app.angular
        image: www/angular
        build: 
            context: ./docker
            args:
                - email=gmail@metlinskyi.com
                - name=Roman Metlinskyi
        ports:
            - 1481:81 # http://localhost:1481/ 
        volumes:
            - .:/usr/share/app
        env_file:
            - docker-compose.env