version: "3.6"
services:
    app:
        container_name: angular
        image: www/angular
        build: 
            context: ./docker
            args:
                - email=gmail@metlinskyi.com
                - name=Roman Metlinskyi
        ports:
            - 4200:4200     # app    http://localhost:4200/ 
            - 9876:9876     # karma  http://localhost:9876/  
        volumes:
            - ./:/usr/share/app
        env_file:
            - ./docker/variables.env